---
- hosts: webapps
  tasks: 
    - name: install apache
      dnf:
        name: httpd
        state: absent
    - name: starting apache service
      systemd:
        name: httpd
        state: started
        enabled: true
    - name: open port 80
      firewalld:
        port: 80/tcp
        state: enabled
        permanent: yes
        immediate: yes
    - name: updating index.html
      copy:
        content: "Welcome to the infrastructure automation ansible server"
        dest: /var/www/html/index.html
      notify: restart apache
  handlers:
    - name: restart apache
      systemd:
        name: httpd
        state: restarted
 
