---

- hosts: login_nodes
  become: true
  tasks:

  - name: update cache
    dnf:
      update_cache: yes

  - name: update installed packages
    dnf:
      name: "*"
      state: latest

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest

  - name: intall git
    dnf:
      name: git
      state: latest

    
